spring.application.name=ots-mail-service
server.port=7880
# use this to generate app password to connect to gmail from app: https://myaccount.google.com/apppasswords
email.username=${EMAIL_USERNAME:defaultUsername}
email.password=${EMAIL_PASSWORD:defaultPassword}
email.host={EMAIL_HOST}
email.from={EMAIL_FROM}
email.port={EMAIL_PORT}
email.subject=Applying for the role of java developer
email.attachmentname=Ankit_Resume_Java.pdf
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.h2.Driver
# HikariCP Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
# Enable H2 Console for Debugging
spring.h2.console.enabled=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
